# Generated by Django 3.2.15 on 2022-10-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221015_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex_code',
            new_name='color',
        ),
    ]
