# Generated by Django 3.2.15 on 2022-10-16 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='time',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
